Add: 회원가입/로그인 엔드포인트 구현, 토큰 발행/인가 구현
wecode-bootcamp-korea/15-2nd-tangWay-backend pull request #2
Opened 2020-12-30 15:03 UTC by Muntari29

>wecode PR message template 및 체크 리스트 입니다. 

## 수정 사항 간략한 한줄 요약
회원가입/로그인 엔드포인트 구현 , 토근 발행/인가 구현
		 
## 수정 사항들 자세한 내용
user/views.py 수정
user/urls.py 수정
user/utils.py 추가
tangway/settings.py 수정

## 기타 질문 및 특이 사항
회원가입 프론트 통신 확인

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [ ] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.

2021-01-01 13:51 UTC, ulfrid requested changes
새해 복 많이 받으세요~!

2021-01-01 13:51 UTC, ulfrid commented on user/tests.py
> +
json 비교 해주세요

2021-01-01 13:51 UTC, ulfrid commented on user/tests.py
> +        self.assertEqual(response.status_code, 201)
signin 의 status가 201인가요? 201은 생성완료 코드입니다. 200으로 변경 부탁드립니다.

2021-01-01 13:51 UTC, ulfrid commented on user/views.py
> +            return JsonResponse({'SUCCESS_access_token' : access_token}, status=201)
```suggestion
            return JsonResponse({'access_token' : access_token}, status=200)
```

2021-01-01 13:51 UTC, ulfrid commented on user/views.py
> +            return JsonResponse({'SUCCESS_access_token' : access_token}, status=201)
굳이 메세지키를 케이스 혼용하는건 별로네요. status 코드로 답변되는 메세지는 제거하셔도 됩니다.

2021-01-01 16:22 UTC, Muntari29 commented on user/tests.py
> +        self.assertEqual(response.status_code, 201)
토큰을 생성해주는것을 DB에 생성해주는것으로 착각하였습니다.
수정하겠습니다!

2021-01-01 16:22 UTC, Muntari29 commented on user/views.py
> +            return JsonResponse({'SUCCESS_access_token' : access_token}, status=201)
수정하겠습니다!

2021-01-01 16:22 UTC, Muntari29 commented on user/tests.py
> +
토큰 비교하는것이 조금 까다로웠지만 해결하였습니다.

2021-01-02 11:12 UTC, ulfrid commented on user/tests.py
> +
위와 같이 따로 토큰 데이터 생성하지 하지 않고 그냥 로그인 통해 받은걸 비교해주시면 됩니다.
access_token = response.json()['access_token'] 이런거요.

2021-01-02 14:53 UTC, Muntari29 commented on user/tests.py
> +
불필요한 코드를 줄일수 있었습니다.
감사합니다

2021-01-04 01:50 UTC, soheon-lee commented on user/utils.py
> +        except User.DoesNotError:
에러이름에서 Exist가 누락된 것 같은데, 이 에러 캐칭 동작 잘 하나요?

2021-01-04 02:20 UTC, Muntari29 commented on user/utils.py
> +        except User.DoesNotError:
![image](https://user-images.githubusercontent.com/65607601/103495612-b7b6fa00-4e7e-11eb-8a29-9358d01308f3.png)

2021-01-04 02:20 UTC, Muntari29 commented on user/utils.py
> +        except User.DoesNotError:
![image](https://user-images.githubusercontent.com/65607601/103495635-cef5e780-4e7e-11eb-965e-32fc4a13bd77.png)

2021-01-04 02:20 UTC, Muntari29 commented on user/utils.py
> +        except User.DoesNotError:
확인 및 수정하였습니다!

2021-01-04 05:21 UTC, soheon-lee commented
LGTM!

2021-01-04 05:21 UTC, merged