[15기 문승희] Add 탑승자 정보 엔드포인트 및 유닛테스트 기능 구현
wecode-bootcamp-korea/15-2nd-tangWay-backend pull request #6
Opened 2021-01-05 05:10 UTC by Muntari29

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
탑승자 정보 엔드포인트 및 유닛테스트 기능 구현
		 
## 수정 사항들 자세한 내용
flight/views.py 수정
fligjt/tests.py 수정
tangway/settings.py 수정

## 기타 질문 및 특이 사항
![image](https://user-images.githubusercontent.com/65607601/103608860-b7daf680-4f5f-11eb-95e9-dba03695ef52.png)

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.
- [x] Git rebase와 squash를 했고 커밋 수가 하나 인것을 확인 했습니다.

2021-01-05 05:50 UTC, ulfrid requested changes
수정 및 테스트 추가 부탁드립니다.

2021-01-05 05:50 UTC, ulfrid commented on flight/tests.py
> +        header   = {'HTTP_Authorization' : self.access_token}
위에 setUp에서 토큰을 생성하지 마시고, 클라이언트로 실제 로그인 한  response로 받은 토큰을 넘겨주세요.

2021-01-05 05:50 UTC, ulfrid commented on flight/tests.py
> +                })
데코레이터에 토큰을 잘 못넘겼을때 나는 테스트도 해주세요. 익셉션 및 유저 드랍하고 조회할 경우의 리턴 등 가능한 경우의 수는 다 테스트 해주십시오.

2021-01-05 05:50 UTC, ulfrid commented on flight/views.py
> +        user    = User.objects.select_related('gender', 'country').get(id=user_id)
굳이 user_id라는 변수를 재사용할 것 아니라면 이런식의 변수 담기는 필요 없을 것 같습니다. 
```
        user    = User.objects.select_related('gender', 'country').get(id=request.user.id)
```

2021-01-05 15:38 UTC, Muntari29 commented on flight/views.py
> +        user    = User.objects.select_related('gender', 'country').get(id=user_id)
해당 변수는 재사용 하지 않습니다.
불필요한 코드를 1줄 더 삭제할 수 있었습니다. 감사합니다.

2021-01-05 15:38 UTC, Muntari29 commented on flight/tests.py
> +        header   = {'HTTP_Authorization' : self.access_token}
해당 Test method에서 여러번 response를 날려도 문제없다는것을 알게되었습니다.
수정하였습니다. 검토 부탁드립니다!

2021-01-05 15:45 UTC, Muntari29 commented on flight/tests.py
> +                })
exception 모두 유닛테스트 구현 하였습니다.

2021-01-06 02:37 UTC, ulfrid commented
LGTM.

2021-01-06 02:37 UTC, merged